In [2]:
import numpy as np

In [2]:
x = np.array([1,3,4,5,6])

In [3]:
print(x)

[1 3 4 5 6]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
y = [1,3,4,5,6,6,8]
print(y)
print(type(y))  # This is just a list. But the numpy thing creats an array. While is multidimentional.

[1, 3, 4, 5, 6, 6, 8]
<class 'list'>


In [6]:
# User defined data in numpy
l = []
for i in range (1,5):
    a = input("Enter the values:\n")
    l.append(a)

In [11]:
#Dimensions in numpy array
# Of 3 types:- 1d 2d and 3d arrays
arr1 = np.array([1,3,4,5]) #1d array.
print(arr1)
print  (arr1.ndim) #ndim is n dimension of array. It gives the number of dimensions of array.


[1 3 4 5]
1


In [4]:
#2 Dimensional array
arr2 = np.array([[1,3,4],[5,6,7]])
print(arr2)
print(arr2.ndim) 

[[1 3 4]
 [5 6 7]]
2


In [5]:
#3 Dimensional array
arr3 = np.array([[1,3,4],[5,6,7],[8,9,0]])
print(arr3)
print(arr3.ndim) 

[[1 3 4]
 [5 6 7]
 [8 9 0]]
2


In [10]:
#n Dimentionl array. Number of start brackets is equal to the number of dimensions.
# arrn = np.array([[[[[[1,3,4,5]]]]]]) // This is valid but requires too much work. Thus use the line below.
arrn = np.array([1,3,4,5], ndmin = 10) # ndmin gives the minimum amout of dimensions of array.
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 3 4 5]]]]]]]]]]
10
